language: node_js
sudo: required
node_js:
  - 0.10.30


    
before_script:
 # - npm link
 # - mkdir -p shippable/codecoverage
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python3.2 python2.7

python:
 - "2.7"

script: ./run_build.sh

after_success:
  - echo $TOTO
  - git remote -v
  - git config --global user.email "rebeenrebwar@gmail.com"
  - git config --global user.name "rebeenrebwar"
  - git checkout master
  - npm version patch
  - git commit -am "[skip ci] bump version"
  - git log --oneline
  - git remote set-url origin git@github.com:rebeenrebwar/travis.git
  - git push origin master
#  - npm run coverage
#  - mv coverage/cobertura-coverage.xml shippable/codecoverage/coverage.xml
#  - mocha test -R mocha-lcov-reporter  && 
#  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose
#  - cat ./coverage/lcov.info | codeclimate
