language: node_js
 
node_js:
  - "5"
    
before_script:
 # - npm link
 # - mkdir -p shippable/codecoverage
 
after_success:
  - echo $TOTO
  - git remote -v
  - git config --global user.email "[rebeenrebwar@gmail.com]"
  - git config --global user.name "[rebeenrebwar]"
 - git checkout master
 - npm version patch
  - git commit -am "[skip ci] bump version"
 - git log --oneline
  - git remote set-url origin [https://github.com/rebeenrebwar/Travis/]
  - git push origin master
#  - npm run coverage
#  - mv coverage/cobertura-coverage.xml shippable/codecoverage/coverage.xml
#  - mocha test -R mocha-lcov-reporter  &&
#  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose
#  - cat ./coverage/lcov.info | codeclimate

